language: node_js
node_js:
  - "10.8.0"
install:
  - npm install

env: SECRET_KEY = chibyke

cache:
  directories:
    - "node_modules"
script:
 - npm test
after_success:
- npm run coveralls
